// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzW8-e3voyo8XFrEdmhH-roAkFHHauUDY',
    appId: '1:676829652596:web:16a1a4b0a7e0c1f3d15321',
    messagingSenderId: '676829652596',
    projectId: 'resume-98381',
    authDomain: 'resume-98381.firebaseapp.com',
    storageBucket: 'resume-98381.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABXBpTQQC0CIrTfCiM-GdwbS6zbbULKL4',
    appId: '1:676829652596:android:abf2c95ca013a68fd15321',
    messagingSenderId: '676829652596',
    projectId: 'resume-98381',
    storageBucket: 'resume-98381.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKTuBCpPQ3tZ8t-2lQYHSrM0kwq_g-j08',
    appId: '1:676829652596:ios:885c4dc4750ce204d15321',
    messagingSenderId: '676829652596',
    projectId: 'resume-98381',
    storageBucket: 'resume-98381.appspot.com',
    iosBundleId: 'com.example.resumeBuilder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKTuBCpPQ3tZ8t-2lQYHSrM0kwq_g-j08',
    appId: '1:676829652596:ios:51a838ac322eb794d15321',
    messagingSenderId: '676829652596',
    projectId: 'resume-98381',
    storageBucket: 'resume-98381.appspot.com',
    iosBundleId: 'com.example.resumeBuilder.RunnerTests',
  );
}
